image: node:${NODE_VERSION}

stages:
  - install
  - test
  - publish
  - release

variables:
  NODE_ENV: 'test'
  NODE_VERSION: '18'
  NPM_TOKEN: $CI_JOB_TOKEN
  NPM_REGISTRY_URL: "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/packages/npm/"
  GITLAB_API_TOKEN: $CI_JOB_TOKEN

cache:
  paths:
    - node_modules/

before_script:
  - 'which node'
  - node --version
  - npm --version

install_dependencies:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour

test:
  stage: test
  dependencies:
    - install_dependencies
  script:
    - npm test

publish:
  stage: publish
  only:
    - tags
  script:
    - echo "//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${NPM_TOKEN}" > ~/.npmrc
    - npm publish --registry ${NPM_REGISTRY_URL}
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour

release:
  stage: release
  only:
    - tags  # Ensure the job only runs for tag-based pipelines
  before_script:
    - 'which node'
    - node --version
    - npm --version
    # Install release-cli
    - curl -o release-cli-linux-amd64.tar.gz -L "https://gitlab.com/gitlab-org/release-cli/-/jobs/artifacts/v0.16.0/download?job=build"
    - tar -xzf release-cli-linux-amd64.tar.gz -C /usr/local/bin
    - chmod +x /usr/local/bin/release-cli
  script:
    - echo "Creating release for tag ${CI_COMMIT_TAG}"
  release:
    name: "Release v${CI_COMMIT_TAG}"
    tag_name: "${CI_COMMIT_TAG}"
    description: "Automated release for version ${CI_COMMIT_TAG}"
    ref: "${CI_COMMIT_TAG}"
    assets:
      links:
        - name: "Download Source Code"
          url: "https://gitlab.com/${CI_PROJECT_PATH}/-/archive/${CI_COMMIT_TAG}/${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tar.gz"
