stages:
  - install
  - test
  - publish

variables:
  NODE_ENV: 'test'
  NODE_VERSION: '18'
  NPM_TOKEN: $CI_JOB_TOKEN
  NPM_REGISTRY_URL: https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/

cache:
  paths:
    - node_modules/

before_script:
  - 'which node'
  - node --version
  - npm --version

install_dependencies:
  stage: install
  image: node:${NODE_VERSION}
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour

test:
  stage: test
  image: node:${NODE_VERSION}
  dependencies:
    - install_dependencies
  script:
    - npm test

publish:
  stage: publish
  image: node:${NODE_VERSION}
  only:
    - tags
  script:
    - echo "//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${NPM_TOKEN}" > ~/.npmrc
    - npm publish --registry ${NPM_REGISTRY_URL}
